### ISSUE TITLE
Check if the given array contains duplicates

### ISSUE THREAD

**Issue by kulcsarrudolf** [stefanalexlupu/derange#3]
If I understand correctly, this algorithm only works with sets, so each element must be unique. This is not implemented yet. My suggestion is to throw an error when the given array contains duplicates.

![image](https://user-images.githubusercontent.com/26814593/90809863-c915c480-e32a-11ea-8a52-5d5e93353c8e.png)

**Comment by kulcsarrudolf** [comment]
I found this on the internet:
```javascript
function checkForDuplicates(array) {
  return new Set(array).size !== array.length
}
```

**Comment by stefanalexlupu** [comment]
Handy method but it won't work for non primitives.

![image](https://user-images.githubusercontent.com/21083175/90898795-b3a6a600-e3cf-11ea-8036-e17929279543.png)

This is actually a valid case for having multiple objects that seem to have the same data but are different instances. Are you familiar with [Stability](https://stackoverflow.com/questions/1517793/what-is-stability-in-sorting-algorithms-and-why-is-it-important#:~:text=A%20sorting%20algorithm%20is%20said,Sort%2C%20Bubble%20Sort%2C%20etc.) of algorithms? I think this is a similar issue, except we want the exact opposite here. Equality is pretty subjective, and in deranging I care more about positions.

This is why this library is based on deranging indexes instead of deranging the actual set. You are therefore guaranteed that an item will not be on the same position it started on, even if an "apparently equal" item will end up on that position.

**Comment by stefanalexlupu** [comment]
As a note, I don't think that guaranteeing "set-ness" of the input should be handled by this library. That check is at best O(n) and it may not even be necessary. This is not even factoring in that we should do a deep compare using something like underscore... too much in my opinion

**Comment by kulcsarrudolf** [comment]
@stefanalexlupu I agree with you. Thank you for your detailed response and providing clarification.
